CREATE DATABASE GYM;

--Tables--

--Member Table--
CREATE TABLE MEMBER(
MemberID INT NOT NULL ,
Category VARCHAR(2000) NOT NULL ,
MemberName VARCHAR(2000) NOT NULL ,
FatherName VARCHAR(2000) DEFAULT 'NULL',
Contactno VARCHAR(2000) DEFAULT 'NULL',
Add_ress VARCHAR(2000) DEFAULT 'NULL',
Weigh VARCHAR(2000) DEFAULT 'NULL',
HeightFT VARCHAR(2000) DEFAULT 'NULL',
HeightIN VARCHAR(2000) DEFAULT 'NULL',
Purpose VARCHAR(2000) DEFAULT 'NULL',
Admissionfee VARCHAR(2000) DEFAULT 'NULL',
DateOfJoining DATE,
Gender VARCHAR(2000) DEFAULT 'NULL'
CONSTRAINT MEMBERPK PRIMARY KEY(MemberID)
)
--DELETE FROM MEMBER WHERE MemberID=
SELECT * FROM MEMBER

--Trainer Table--
CREATE TABLE TRAINER(
TrainerID INT NOT NULL,
TrainerName VARCHAR(2000) DEFAULT 'NULL',
Add_ress VARCHAR(2000) DEFAULT 'NULL',
Contactno VARCHAR(2000) DEFAULT 'NULL',
ExperienceTime VARCHAR(2000) DEFAULT 'NULL',
DateOfJoining DATE,
Password_T VARCHAR(2000) DEFAULT 'NULL'
CONSTRAINT TRAINERPK PRIMARY KEY(TrainerID)
)
SELECT * FROM TRAINER

--Package Table--
CREATE TABLE PACKAGE(
PackageID INT NOT NULL,
PackageName VARCHAR(2000) DEFAULT 'NULL',
Duration VARCHAR(2000) DEFAULT 'NULL',
Price VARCHAR(2000) DEFAULT 'NULL'
CONSTRAINT PACKAGEPK PRIMARY KEY(PackageID)
)
SELECT * FROM PACKAGE

--Salary Table--
CREATE TABLE SALARY(
SalaryID INT NOT NULL,
Tittle VARCHAR(2000) DEFAULT 'NULL',
PayAmount VARCHAR(2000) DEFAULT 'NULL'
CONSTRAINT SALARYPK PRIMARY KEY(SalaryID)
)
SELECT * FROM SALARY

--Pay Table--
CREATE TABLE PAY(
PayID INT NOT NULL,
TrainerID INT,
Date_p DATE,
PayAmount VARCHAR(2000) DEFAULT 'NULL'
CONSTRAINT PAYPK PRIMARY KEY(PayID),
CONSTRAINT PAYFK1 FOREIGN KEY(TrainerID) REFERENCES TRAINER(TrainerID)
)
SELECT * FROM SALARY

--Pay Table--
CREATE TABLE PAY(
PayID INT NOT NULL,
TrainerID INT,
Date_p DATE
CONSTRAINT PAYPK PRIMARY KEY(PayID),
CONSTRAINT PAYFK1 FOREIGN KEY(TrainerID) REFERENCES TRAINER(TrainerID)
)
SELECT * FROM PAY

--Fee Table--
CREATE TABLE FEE(
FeeID INT NOT NULL,
MemberID INT,
Date_f DATE
CONSTRAINT FEEPK PRIMARY KEY(FeeID),
CONSTRAINT FEEFK1 FOREIGN KEY(MemberID) REFERENCES MEMBER(MemberID)
)
SELECT * FROM FEE

--Train Table--
CREATE TABLE TRAIN(
TrainerID INT,
MemberID INT
CONSTRAINT TRAINFK1 FOREIGN KEY(TrainerID) REFERENCES TRAINER(TrainerID),
CONSTRAINT TRAINFK2 FOREIGN KEY(MemberID) REFERENCES MEMBER(MemberID),
CONSTRAINT TRAINPK PRIMARY KEY(TrainerID,MemberID)
)
SELECT * FROM TRAIN

--End TABLES--